# Generated by Django 3.1.7 on 2021-04-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210405_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_created',)},
        ),
    ]
