# Generated by Django 3.1.7 on 2021-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='goal',
            field=models.TextField(blank=True, default='What are your study goals?', max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, default='What are your study goals?', max_length=150, null=True),
        ),
    ]
