# Generated by Django 3.1.7 on 2021-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20210316_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='tutorial',
            field=models.ManyToManyField(blank=True, to='hub.Tutorial'),
        ),
    ]
