# Generated by Django 3.1.7 on 2021-03-18 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0003_auto_20210316_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fb_url', models.CharField(blank=True, max_length=150, null=True)),
                ('ig_url', models.CharField(blank=True, max_length=150, null=True)),
                ('blog_url', models.CharField(blank=True, max_length=150, null=True)),
                ('goal', models.CharField(blank=True, default='What is your learning goals?', max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
