# Generated by Django 3.1.7 on 2021-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20210318_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, default='What is your learning goals?', max_length=250, null=True),
        ),
    ]
