# Generated by Django 3.1.7 on 2021-03-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20210318_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ('-last_updated',)},
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='goal',
            field=models.CharField(blank=True, default='What is your study goals?', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, default='What is your study goals?', max_length=150, null=True),
        ),
    ]
