# Generated by Django 3.1.7 on 2021-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_auto_20210330_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='goal',
            field=models.TextField(blank=True, default='What is your study goals?', max_length=550, null=True),
        ),
    ]
